//
//  DetailPresenter.swift
//  PokeDeck
//
//  Created by Fachri Work on 7/27/17.
//  Copyright (c) 2017 Decadev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic
{
    func presentPokemonDetail(response: Detail.PokeDex.Response)
}

class DetailPresenter: DetailPresentationLogic
{

    weak var viewController: DetailDisplayLogic?
    
    // MARK: Do something
    func presentPokemonDetail(response: Detail.PokeDex.Response) {
        let viewModel = Detail.PokeDex.ViewModel(success: response.success,pokemon: response.pokemon)
        viewController?.displayPokemon(viewModel: viewModel)
    }
}
