//
//  DeckPresenter.swift
//  PokeDeck
//
//  Created by Fachri Work on 7/27/17.
//  Copyright (c) 2017 Decadev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DeckPresentationLogic
{
  func presentPokemon(response: Deck.Pokedex.Response)
}

class DeckPresenter: DeckPresentationLogic
{
  weak var viewController: DeckDisplayLogic?
  
  // MARK: Do something
  
  func presentPokemon(response: Deck.Pokedex.Response)
  {
    let viewModel = Deck.Pokedex.ViewModel(success: response.success, pokemon: response.pokemon)
    viewController?.displayPokemon(viewModel: viewModel)
  }
}
