//
//  DeckRouter.swift
//  PokeDeck
//
//  Created by Fachri Work on 7/27/17.
//  Copyright (c) 2017 Decadev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DeckRoutingLogic
{
    func routeToDetail(pokemon: AnyObject, segue: UIStoryboardSegue?)
}

protocol DeckDataPassing
{
    var dataStore: DeckDataStore? { get }
}

class DeckRouter: NSObject, DeckRoutingLogic, DeckDataPassing
{
    
    weak var viewController: DeckViewController?
    var dataStore: DeckDataStore?
    
    // MARK: Routing
    
    func routeToDetail(pokemon: AnyObject, segue: UIStoryboardSegue? = nil)
    {
        let pokeName = pokemon as! Pokemon
        print(pokeName)
        
      if let segue = segue {
        let destinationVC = segue.destination as! DetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToDetail(pokemon: pokemon as! Pokemon, destination: &destinationDS)
      } else {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "DetailViewController") as! DetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToDetail(pokemon: pokemon as! Pokemon, destination: &destinationDS)
        navigateToDetail(source: viewController!, destination: destinationVC)
      }
    }
    
    // MARK: Navigation
    
    func navigateToDetail(source: DeckViewController, destination: DetailViewController)
    {
      source.show(destination, sender: nil)
    }
    
    //MARK: Passing data
    
    func passDataToDetail(pokemon: Pokemon, destination: inout DetailDataStore)
    {
        print(pokemon)
      destination.pokemon = pokemon
    }
}
