//
//  DeckInteractor.swift
//  PokeDeck
//
//  Created by Fachri Work on 7/27/17.
//  Copyright (c) 2017 Decadev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DeckBusinessLogic
{
    func fetchPokemon(request: Deck.Pokedex.Request)
}

protocol DeckDataStore
{
    var pokemon: [Pokemon] { get }
}

class DeckInteractor: DeckBusinessLogic, DeckDataStore
{
    var presenter: DeckPresentationLogic?
    var worker = DeckWorker()
    var pokemon: [Pokemon] = []
    
    // MARK: Do something
    
    func fetchPokemon(request: Deck.Pokedex.Request)
    {
        
        worker.fetchPokemon { (success, pokemon) in
            self.pokemon = pokemon
            
            let response = Deck.Pokedex.Response(success: success, pokemon: pokemon)
            self.presenter?.presentPokemon(response: response)
        }
    }
}
